### PR TITLE
Forward the SOURCE as NodeURI

### PR DESCRIPTION
**Pull request by aliariff**
Fix https://github.com/sparql-generate/sparql-generate/issues/63

### CODE REVIEW

**Comment by aliariff** [comment]
Hi @maximelefrancois86,

Is there any chance this get review?

**Comment by maximelefrancois86** [comment]
I'm afraid there is a lot more things that need to be changeD consequently. 
This would change the behaviour of many methods, that expect the actual content of the source (a literal) instead of the URI.

If you want to work on this issue, I suggest to create a new subclass of `Node`,  for example `SourceNode`, that can be printed out as a literal, and implements `AutoCloseable`

**Comment by aliariff** [comment]
Do you mean that this new subclass, will kind of mimic what `Node_Literal` does? because I saw there is a lot of checking like `node.isLiteral()` in the iterator implementation. Will this new subclass return `true` for those checking?

**Comment by maximelefrancois86** [comment]
Yes, maybe even a subclass of `Node_Literal` itself, where the `label` member is not used, but instead there is some way to open it, consume it, then close it ? 

The methods `getLiteral`, `getLexicalForm`, etc, could read the whole stream and cache the value,
In some iterator or mapping functions, we could use the stream itself

**Comment by aliariff** [comment]
Hi @maximelefrancois86 

We currently have our own workaround for now to this particular issue. Even though that the case, this issue about OOM still exists and needs further investigation & fixing in the future.

So for now I will just close this pull request.

**Pull request closed without merging**
