### PR TITLE
Add option to fail on exception

### PR DESCRIPTION
**Pull request by aliariff**
Hi @maximelefrancois86 

Here is the solution as we discussed in #129

### CODE REVIEW

**Comment by aliariff** [comment]
Hi @maximelefrancois86 

Got time to review this?

**Comment by maximelefrancois86** [comment]
It depends on you I guess. Would you have other issues or new features in mind that could be worth for a new milestone ? I guess at this stage a new minor increment 2.1.0 would be good ?

**Comment by aliariff** [comment]
Yes I think a new release will be good, and minor version also good idea.

**Comment by aliariff** [comment]
Hi @maximelefrancois86,

got time for making a new release?

**Pull request merged**
